### ISSUE TITLE
ログインユーザー情報取得のmock APIの作成

### ISSUE THREAD

**Issue by shuheeeei** [80PercentBloom/enzivia-no-izumi#27]
Next.jsのAPI Routeで作成したい
内容はとりあえずnameとプロフィール画像のURL

**Comment by 97liar** [comment]
@shuheeeei こちらは「Foo」という名前のアカウントが存在しているとして、「Foo」がログインした時に返ってくるデータのイメージでしょうか？クエリパラメータが必要を確認したいです。
